// CalendarEngine.js - Logic to handle Google/Outlook Calendar Exports
export const syncToCalendar = (task, owner, setStatus) => {
    setStatus(`Syncing: ${task}...`);
    
    // Virtual Calendar Event Data
    const event = {
        title: `Meeting Action: ${task}`,
        description: `Assigned to: ${owner}. Generated by MeetingMind AI`,
        startTime: new Date().toISOString(),
        endTime: new Date(Date.now() + 3600000).toISOString(), // 1 hour later
    };

    // Yahan hum Google Calendar Link generate kar rahe hain
    const googleUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&details=${encodeURIComponent(event.description)}&dates=${event.startTime.replace(/-|:|\.\d\d\d/g, "")}/${event.endTime.replace(/-|:|\.\d\d\d/g, "")}`;

    // Simulation of Neural Sync
    setTimeout(() => {
        window.open(googleUrl, '_blank');
        setStatus("Calendar Synced Successfully!");
        setTimeout(() => setStatus(""), 3000);
    }, 1200);
};

export const downloadICSFile = (task, owner) => {
    // Standard Calendar Format (.ics) for Outlook/Apple
    const icsData = `BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:${task}
DESCRIPTION:Owner: ${owner} - MeetingMind AI
DTSTART:${new Date().toISOString().replace(/-|:|\.\d\d\d/g, "")}
END:VEVENT
END:VCALENDAR`;

    const blob = new Blob([icsData], { type: 'text/calendar;charset=utf-8' });
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.setAttribute('download', 'meeting-event.ics');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};